name: Docker Deployment Pipeline
on:
  push:
    branches: [main]
    tags: ['release-*']

jobs:
  validate-project: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 
    - name: Check required project files
      run: |
        echo "Validating essential files..."
        if [[ ! -f "script.py" || ! -f "requirements.txt" || ! -f "Dockerfile" ]]; then
          echo "Missing required files!"
          exit 1
        fi
        echo "All required files present"

  containerize-and-deploy:  
    runs-on: ubuntu-latest
    needs: validate-project
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  
      
    - name: Authenticate with Docker Hub
      uses: docker/login-action@v2  
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4  
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/taller0352
        
    - name: Build and publish Docker image
      uses: docker/build-push-action@v3  
      with:
        context: .
        push: true
        cache-from: type=gha  
        cache-to: type=gha,mode=max
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/taller0352:latest
          ${{ secrets.DOCKER_USERNAME }}/taller0352:${{ github.run_id }}
