name: Sample Python Test

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Check required files
      run: |
        if [ ! -f "sample.py" ]; then
          echo "Error: sample.py not found!"
          exit 1
        fi
        if [ ! -f "requirements.txt" ]; then
          echo "Error: requirements.txt not found!"
          exit 1
        fi
        if [ ! -f "Dockerfile" ]; then
          echo "Error: Dockerfile not found!"
          exit 1
        fi
        echo "All required files exist"
  
  test:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify Flask
      run: |
        python -c "import flask; print('Flask is installed correctly')"
    
    - name: Verify Flask version
      run: |
        pip show flask
    
    - name: Run simple test
      run: |
        python -c "from sample import app; print('App imported successfully')"
